# Generated by Django 3.2.8 on 2021-11-05 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(max_length=5000)),
                ('author', models.CharField(max_length=300)),
                ('created_date', models.DateField()),
                ('image', models.URLField(default=None, null=True)),
                ('linktosite', models.URLField(default=None, null=True)),
            ],
        ),
    ]
